repos:
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      exclude: '^(api/database/)'
- repo: https://github.com/ambv/black
  rev: 24.4.2
  hooks:
    - id: black
      exclude: '^(api/database/)'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
      exclude: '(^api/database/)'
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
    - id: flake8
      additional_dependencies: [flake8-walrus==1.2.0]
      exclude: '^(api/database/)'
